# Generated by Django 4.2.4 on 2023-09-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
