# Generated by Django 4.2.4 on 2023-08-15 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bugs.project'),
            preserve_default=False,
        ),
    ]
